$(document).ready(function(){
    $('#tomatoLate').click(function(){
        $('.tomatoLatetext').toggle();
    });
    $('#tomatoYellow').click(function(){
        $('.tomatoYellowtext').toggle();
    });
    $('#leafMinor').click(function(){
        $('.leafMinortext').toggle();
    });
});